### ISSUE TITLE
Figma Store용 이미지 등록

### ISSUE THREAD

**Issue by dusskapark** [dusskapark/iconography-ml#3]
- 앱 아이콘: 128x128 png
- 커버 아트: 1920x960 png (safe-area: 1600x960)

**Comment by dusskapark** [comment]
@hiteq

**Comment by hiteq** [comment]
App Icon: 128x128 png
![meta-icon-f](https://user-images.githubusercontent.com/5396900/163117121-7a29d1bc-b446-4f26-ae8e-7eefd6213e2e.png)

Cover Art: 1920x960 png (safe-area: 1600x960)
![meta-desc-img](https://user-images.githubusercontent.com/5396900/163117291-2b195950-824c-4aa6-ae2e-cdb4925c1f0a.png)

Figma profile:
[https://www.figma.com/@heetaekwoo](https://www.figma.com/@heetaekwoo)

**Comment by dusskapark** [comment]
Thanks! @hiteq
